### ISSUE TITLE
Resource statistics

### ISSUE THREAD

**Issue by ls-2018** [vladimirvivien/ktop#39]
I initially thought the cpu and memory statistics were utilization, which I thought was amazing because I didn't deploy metrics servers.
After the meeting, I found that the documentation said that these were requests and limits for resources, but I found that these were not the same as what I actually set in yaml.
 
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/38821215/235041675-1d4aa13f-8127-4d5c-8b13-949a2fda7f21.png">

![image](https://user-images.githubusercontent.com/38821215/235042174-a9cc7fce-8699-48a9-97a0-3fffef732443.png)

There's a big difference in memory here

**Comment by vladimirvivien** [comment]
Hi thank you for reporting the issue.
The software will use resource requests if it does not find a metrics server.
If one is found, it will try to use it to report resource consumptions.

Can you provide some additional detail?
- Are you using a metrics server ?
- Are you seeing issues with other pods ?
- What version of the software are you using ?

**Comment by ls-2018** [comment]
``` 
~  ktop version
Connected to: https://127.0.0.1:57586

 _    _
| | _| |_ ___  _ __
| |/ / __/ _ \| '_ \
|   <| || (_) | |_) |
|_|\_\\__\___/| .__/
              |_|
Version v0.3.5

```


```
echo 'kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "EphemeralContainers": true
nodes:
- role: control-plane
  image: kindest/node:v1.26.0 
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP 
- role: worker
  image: kindest/node:v1.26.0
  labels:
    zone: c  
' >/tmp/kind.yaml

kind create cluster --config /tmp/kind.yaml
```
